# MantisBT dependabot configuration

version: 2
updates:

# Check for Composer updates every day
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: erusev/parsedown
    versions:
    - ">= 1.7.2.a, < 1.7.3"

# Check for GitHub Actions updates every month
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
