<?php
# MantisBT - A PHP based bugtracking system

# MantisBT is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# MantisBT is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with MantisBT.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Test cases for API Token API within mantis
 *
 * @package    Tests
 * @subpackage ApiTokenAPI
 * @copyright  Copyright MantisBT Team - mantisbt-dev@lists.sourceforge.net
 * @link       http://www.mantisbt.org
 *
 * @noinspection PhpIllegalPsrClassPathInspection
 */

namespace Mantis\tests\Mantis;

/**
 * PHPUnit tests for API Token API
 */
class ApiTokenApiTest extends MantisCoreBase {

	/**
	 * A sample token of the right length (API_TOKEN_LENGTH), using the same
	 * URI-safe base64 alphabet as tokens generated by api_token_create().
	 */
	const SAMPLE_TOKEN = 'AbCdEfGhIjKlMnOpQrStUvWxYz012345';

	/**
	 * The sample token must stay the length a real token has, otherwise the
	 * parser cases below stop resembling anything api_token_get_user() would
	 * accept. Fails loudly if API_TOKEN_LENGTH ever changes.
	 * @return void
	 */
	public function testSampleTokenMatchesApiTokenLength() {
		$this->assertEquals( API_TOKEN_LENGTH, strlen( self::SAMPLE_TOKEN ) );
	}

	/**
	 * Tests api_token_parse_credentials()
	 *
	 * @dataProvider providerParseCredentials
	 *
	 * @param string $p_credentials The Authorization header credentials.
	 * @param string $p_expected    The expected plain token candidate.
	 * @return void
	 */
	public function testParseCredentials( $p_credentials, $p_expected ) {
		$this->assertEquals( $p_expected, api_token_parse_credentials( $p_credentials ) );
	}

	/**
	 * Data provider for testParseCredentials().
	 *
	 * @return array [ credentials, expected ]
	 */
	public static function providerParseCredentials() {
		$t_token = self::SAMPLE_TOKEN;

		return array(
			# The bare token form remains supported, unchanged.
			'bare token' => array( $t_token, $t_token ),

			# RFC 6750 bearer form, with case-insensitive scheme matching.
			'Bearer' => array( 'Bearer ' . $t_token, $t_token ),
			'bearer lowercase' => array( 'bearer ' . $t_token, $t_token ),
			'BEARER uppercase' => array( 'BEARER ' . $t_token, $t_token ),
			'BeArEr mixed case' => array( 'BeArEr ' . $t_token, $t_token ),

			# Multiple spaces after the scheme are tolerated, as is surrounding
			# whitespace around the whole header value.
			'extra spaces after scheme' => array( 'Bearer    ' . $t_token, $t_token ),
			'surrounding whitespace, bearer' => array( '  Bearer ' . $t_token . '  ', $t_token ),
			'surrounding whitespace, bare' => array( '  ' . $t_token . '  ', $t_token ),

			# RFC 6750 defines the separator as 1*SP, so a HTAB is not a valid
			# scheme separator: the value is passed through as-is rather than
			# being treated as a bearer token.
			'tab after scheme is not a separator' => array( "Bearer\t" . $t_token, "Bearer\t" . $t_token ),

			# Other schemes are left untouched, so they keep failing token
			# validation exactly as they did before.
			'basic scheme' => array( 'Basic dXNlcjpwYXNz', 'Basic dXNlcjpwYXNz' ),

			# Degenerate inputs must not produce a token-shaped result.
			'empty' => array( '', '' ),
			'whitespace only' => array( "  \t ", '' ),
			'scheme without token' => array( 'Bearer', 'Bearer' ),
			'scheme with trailing space only' => array( 'Bearer ', 'Bearer' ),

			# 'Bearer' without a separating space is not a scheme, so the value
			# is passed through as-is rather than silently truncated.
			'no separator after scheme' => array( 'Bearer' . $t_token, 'Bearer' . $t_token ),
		);
	}

	/**
	 * A bearer-prefixed token must resolve to the same user as the bare token.
	 *
	 * Uses the test suite's API token, which is created against the test
	 * instance's database by tests/ci_create_api_token.php.
	 *
	 * @return void
	 */
	public function testParsedBearerTokenResolvesSameUserAsBareToken() {
		if( empty( $GLOBALS['MANTIS_TESTSUITE_API_TOKEN'] ) ) {
			$this->markTestSkipped( 'MANTIS_TESTSUITE_API_TOKEN not configured in bootstrap.php' );
		}

		self::dbConnect();

		$t_token = $GLOBALS['MANTIS_TESTSUITE_API_TOKEN'];
		$t_user_id = api_token_get_user( api_token_parse_credentials( $t_token ) );
		$this->assertNotFalse( $t_user_id, 'Bare test suite token should resolve to a user' );

		$this->assertEquals(
			$t_user_id,
			api_token_get_user( api_token_parse_credentials( 'Bearer ' . $t_token ) )
		);
	}
}
